// Generated by gencpp from file mlmc_msgs/PID.msg
// DO NOT EDIT!


#ifndef MLMC_MSGS_MESSAGE_PID_H
#define MLMC_MSGS_MESSAGE_PID_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mlmc_msgs
{
template <class ContainerAllocator>
struct PID_
{
  typedef PID_<ContainerAllocator> Type;

  PID_()
    : p(0.0)
    , i(0.0)
    , d(0.0)
    , ffd0(0.0)
    , ffd1(0.0)  {
    }
  PID_(const ContainerAllocator& _alloc)
    : p(0.0)
    , i(0.0)
    , d(0.0)
    , ffd0(0.0)
    , ffd1(0.0)  {
  (void)_alloc;
    }



   typedef float _p_type;
  _p_type p;

   typedef float _i_type;
  _i_type i;

   typedef float _d_type;
  _d_type d;

   typedef float _ffd0_type;
  _ffd0_type ffd0;

   typedef float _ffd1_type;
  _ffd1_type ffd1;





  typedef boost::shared_ptr< ::mlmc_msgs::PID_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mlmc_msgs::PID_<ContainerAllocator> const> ConstPtr;

}; // struct PID_

typedef ::mlmc_msgs::PID_<std::allocator<void> > PID;

typedef boost::shared_ptr< ::mlmc_msgs::PID > PIDPtr;
typedef boost::shared_ptr< ::mlmc_msgs::PID const> PIDConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mlmc_msgs::PID_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mlmc_msgs::PID_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mlmc_msgs::PID_<ContainerAllocator1> & lhs, const ::mlmc_msgs::PID_<ContainerAllocator2> & rhs)
{
  return lhs.p == rhs.p &&
    lhs.i == rhs.i &&
    lhs.d == rhs.d &&
    lhs.ffd0 == rhs.ffd0 &&
    lhs.ffd1 == rhs.ffd1;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mlmc_msgs::PID_<ContainerAllocator1> & lhs, const ::mlmc_msgs::PID_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mlmc_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mlmc_msgs::PID_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mlmc_msgs::PID_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mlmc_msgs::PID_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mlmc_msgs::PID_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mlmc_msgs::PID_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mlmc_msgs::PID_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mlmc_msgs::PID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a76881aad551f4c46d9753b2549d471b";
  }

  static const char* value(const ::mlmc_msgs::PID_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa76881aad551f4c4ULL;
  static const uint64_t static_value2 = 0x6d9753b2549d471bULL;
};

template<class ContainerAllocator>
struct DataType< ::mlmc_msgs::PID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mlmc_msgs/PID";
  }

  static const char* value(const ::mlmc_msgs::PID_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mlmc_msgs::PID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 p\n"
"float32 i\n"
"float32 d\n"
"float32 ffd0\n"
"float32 ffd1\n"
;
  }

  static const char* value(const ::mlmc_msgs::PID_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mlmc_msgs::PID_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.p);
      stream.next(m.i);
      stream.next(m.d);
      stream.next(m.ffd0);
      stream.next(m.ffd1);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PID_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mlmc_msgs::PID_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mlmc_msgs::PID_<ContainerAllocator>& v)
  {
    s << indent << "p: ";
    Printer<float>::stream(s, indent + "  ", v.p);
    s << indent << "i: ";
    Printer<float>::stream(s, indent + "  ", v.i);
    s << indent << "d: ";
    Printer<float>::stream(s, indent + "  ", v.d);
    s << indent << "ffd0: ";
    Printer<float>::stream(s, indent + "  ", v.ffd0);
    s << indent << "ffd1: ";
    Printer<float>::stream(s, indent + "  ", v.ffd1);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MLMC_MSGS_MESSAGE_PID_H
