// Generated by gencpp from file mlmc/RunTest.msg
// DO NOT EDIT!


#ifndef MLMC_MESSAGE_RUNTEST_H
#define MLMC_MESSAGE_RUNTEST_H

#include <ros/service_traits.h>


#include <mlmc/RunTestRequest.h>
#include <mlmc/RunTestResponse.h>


namespace mlmc
{

struct RunTest
{

typedef RunTestRequest Request;
typedef RunTestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RunTest
} // namespace mlmc


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mlmc::RunTest > {
  static const char* value()
  {
    return "db324d824adf6dca3d2931e8d8ebd4ef";
  }

  static const char* value(const ::mlmc::RunTest&) { return value(); }
};

template<>
struct DataType< ::mlmc::RunTest > {
  static const char* value()
  {
    return "mlmc/RunTest";
  }

  static const char* value(const ::mlmc::RunTest&) { return value(); }
};


// service_traits::MD5Sum< ::mlmc::RunTestRequest> should match
// service_traits::MD5Sum< ::mlmc::RunTest >
template<>
struct MD5Sum< ::mlmc::RunTestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mlmc::RunTest >::value();
  }
  static const char* value(const ::mlmc::RunTestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mlmc::RunTestRequest> should match
// service_traits::DataType< ::mlmc::RunTest >
template<>
struct DataType< ::mlmc::RunTestRequest>
{
  static const char* value()
  {
    return DataType< ::mlmc::RunTest >::value();
  }
  static const char* value(const ::mlmc::RunTestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mlmc::RunTestResponse> should match
// service_traits::MD5Sum< ::mlmc::RunTest >
template<>
struct MD5Sum< ::mlmc::RunTestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mlmc::RunTest >::value();
  }
  static const char* value(const ::mlmc::RunTestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mlmc::RunTestResponse> should match
// service_traits::DataType< ::mlmc::RunTest >
template<>
struct DataType< ::mlmc::RunTestResponse>
{
  static const char* value()
  {
    return DataType< ::mlmc::RunTest >::value();
  }
  static const char* value(const ::mlmc::RunTestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MLMC_MESSAGE_RUNTEST_H
