// Generated by gencpp from file mlmc/RunTestRequest.msg
// DO NOT EDIT!


#ifndef MLMC_MESSAGE_RUNTESTREQUEST_H
#define MLMC_MESSAGE_RUNTESTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mlmc
{
template <class ContainerAllocator>
struct RunTestRequest_
{
  typedef RunTestRequest_<ContainerAllocator> Type;

  RunTestRequest_()
    : start(false)  {
    }
  RunTestRequest_(const ContainerAllocator& _alloc)
    : start(false)  {
  (void)_alloc;
    }



   typedef uint8_t _start_type;
  _start_type start;





  typedef boost::shared_ptr< ::mlmc::RunTestRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mlmc::RunTestRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RunTestRequest_

typedef ::mlmc::RunTestRequest_<std::allocator<void> > RunTestRequest;

typedef boost::shared_ptr< ::mlmc::RunTestRequest > RunTestRequestPtr;
typedef boost::shared_ptr< ::mlmc::RunTestRequest const> RunTestRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mlmc::RunTestRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mlmc::RunTestRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mlmc::RunTestRequest_<ContainerAllocator1> & lhs, const ::mlmc::RunTestRequest_<ContainerAllocator2> & rhs)
{
  return lhs.start == rhs.start;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mlmc::RunTestRequest_<ContainerAllocator1> & lhs, const ::mlmc::RunTestRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mlmc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mlmc::RunTestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mlmc::RunTestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mlmc::RunTestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mlmc::RunTestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mlmc::RunTestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mlmc::RunTestRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mlmc::RunTestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "676aa7bfb3ec2071e814f2368dfd5fb5";
  }

  static const char* value(const ::mlmc::RunTestRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x676aa7bfb3ec2071ULL;
  static const uint64_t static_value2 = 0xe814f2368dfd5fb5ULL;
};

template<class ContainerAllocator>
struct DataType< ::mlmc::RunTestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mlmc/RunTestRequest";
  }

  static const char* value(const ::mlmc::RunTestRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mlmc::RunTestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool start\n"
;
  }

  static const char* value(const ::mlmc::RunTestRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mlmc::RunTestRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RunTestRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mlmc::RunTestRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mlmc::RunTestRequest_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.start);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MLMC_MESSAGE_RUNTESTREQUEST_H
