// Generated by gencpp from file mlmc/RunTestResponse.msg
// DO NOT EDIT!


#ifndef MLMC_MESSAGE_RUNTESTRESPONSE_H
#define MLMC_MESSAGE_RUNTESTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mlmc
{
template <class ContainerAllocator>
struct RunTestResponse_
{
  typedef RunTestResponse_<ContainerAllocator> Type;

  RunTestResponse_()
    : finished(false)  {
    }
  RunTestResponse_(const ContainerAllocator& _alloc)
    : finished(false)  {
  (void)_alloc;
    }



   typedef uint8_t _finished_type;
  _finished_type finished;





  typedef boost::shared_ptr< ::mlmc::RunTestResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mlmc::RunTestResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RunTestResponse_

typedef ::mlmc::RunTestResponse_<std::allocator<void> > RunTestResponse;

typedef boost::shared_ptr< ::mlmc::RunTestResponse > RunTestResponsePtr;
typedef boost::shared_ptr< ::mlmc::RunTestResponse const> RunTestResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mlmc::RunTestResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mlmc::RunTestResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mlmc::RunTestResponse_<ContainerAllocator1> & lhs, const ::mlmc::RunTestResponse_<ContainerAllocator2> & rhs)
{
  return lhs.finished == rhs.finished;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mlmc::RunTestResponse_<ContainerAllocator1> & lhs, const ::mlmc::RunTestResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mlmc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mlmc::RunTestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mlmc::RunTestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mlmc::RunTestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mlmc::RunTestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mlmc::RunTestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mlmc::RunTestResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mlmc::RunTestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2797c797e620a950ba704492d72873b";
  }

  static const char* value(const ::mlmc::RunTestResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2797c797e620a95ULL;
  static const uint64_t static_value2 = 0x0ba704492d72873bULL;
};

template<class ContainerAllocator>
struct DataType< ::mlmc::RunTestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mlmc/RunTestResponse";
  }

  static const char* value(const ::mlmc::RunTestResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mlmc::RunTestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool finished\n"
;
  }

  static const char* value(const ::mlmc::RunTestResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mlmc::RunTestResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.finished);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RunTestResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mlmc::RunTestResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mlmc::RunTestResponse_<ContainerAllocator>& v)
  {
    s << indent << "finished: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.finished);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MLMC_MESSAGE_RUNTESTRESPONSE_H
